### ISSUE TITLE
Package install issue

### ISSUE THREAD

**Issue by smartell** [seacode/rsimGmacs#3]
I get the following error trying to load the package directly from github

Downloading github repo seacode/rsimGmacs@master
Installing rsimGmacs
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/4g/f1g2109d0t1b01tbhv3y315r0000gp/T/RtmpN2tv6s/devtoolsb576723b3752/seacode-rsimGmacs-0603855'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
  --install-tests 
- installing _source_ package ‘rsimGmacs’ ...
  *\* R
  *\* preparing package for lazy loading
  Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/tcltk/libs/tcltk.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.1/Resources/library/tcltk/libs/tcltk.so, 10): Library not loaded: /usr/X11/lib/libXft.2.dylib
  Referenced from: /usr/local/lib/libtk8.6.dylib
  Reason: image not found
  ERROR: lazy loading failed for package ‘rsimGmacs’
- removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/rsimGmacs’
  Error: Command failed (1)

**Comment by wStockhausen** [comment]
The package requires the tcltk package to be installed on the user's machine. It was inadvertently left out of the "Imports" section of the DESCRIPTION file. This has now been corrected (version 0.5.1). In addition, required packages are now listed in the README file.
